migrations:
	pipenv run python3 manage.py makemigrations

migrate:
	pipenv run python3 manage.py migrate

start:
	pipenv run python3 manage.py runserver

test:
	pipenv run python3 manage.py test

shell:
	pipenv shell
