# Generated by Django 3.1.1 on 2020-09-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfBody',
        ),
    ]
