# Generated by Django 3.1.2 on 2020-10-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_auto_20201019_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='agent_fax',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='agent_license',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='agent_mls',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='agent_phone',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attached_gas_grill_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attached_tv_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attorney_address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attorney_email',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attorney_fax',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attorney_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='attorney_phone',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='balance_of_earnest_money_amount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='balance_of_earnest_money_due_date',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='broker_address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='broker_email',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='brokerage',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='brokerage_for_earnest_money',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='brokerage_license',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='brokerage_mls',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='built_int_or_attached_shelves_or_cabinets_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='buyer_interest_rate',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='buyer_loan_term',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='buyer_loan_to_value',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='ceiling_fan_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='central_air_conditioner_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='central_humidifier_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='closing_date',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='credit_buyer_at_closing_if_no_percentage',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='credit_buyer_at_closing_if_yes_amount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='designated_agent',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='dishwasher_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='dryer_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='dual_agent_broker_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='electronic_air_filter_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='electronic_garage_door_with_remote_unit_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='existing_storms_and_screens_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='fireplace_gas_log_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='fireplace_screen_and_equipment_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='firewood_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='garbage_disposal_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='home_warranty_amount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='how_buyer_deposits_earnest_money',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='initial_earnest_money_amount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='initial_earnest_money_due_date',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='intercom_system_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lender_address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lender_company',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lender_email',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lender_fax',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lender_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lender_phone',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='length_of_attorney_review',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='length_of_inspection_period',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='lighting_fixtures_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='microwave_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='mortgage_contingency_date',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='multimedia_equipment_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='offer_date',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='other_equipment_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='oven_or_range_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='purchase_price',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='radiator_covers_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='refrigerator_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='satellite_dish_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='security_system_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='smoke_and_carbon_monoxide_detectors_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='sump_pump_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='trash_compactor_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='tv_antenna_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='washer_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='water_softner_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='window_air_conditioner_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persistentuserchoice',
            name='window_treatments_details',
            field=models.TextField(default=None, null=True),
        ),
    ]
