# Generated by Django 3.1.2 on 2020-11-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0016_auto_20201105_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentuserchoice',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='buyer_email',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='buyer_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='deeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='deliver_association',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='historical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='homeowner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='homeowner_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='homeowner_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='limited_common_element',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='offer_deadline',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='parking_pin',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='parking_space_numbers',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='prorated',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='riders_or_addendums',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='seller_email',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='seller_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='senior_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='special_assessment_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persistentuserchoice',
            name='special_assessment_yes',
            field=models.BooleanField(default=False),
        ),
    ]
